import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}> 
       <nav style={{
        background:"teal", 
        width:"100%",
        fontSize:"50px",
        display:"flex",
        justifyContent:"center",
        alignItems:"center"
        
       }}>
      
       <Link   style={{marginRight:"200px"}} href="/">

        Home
        
        </Link>

        <Link style={{marginRight:"0"}} href="/posts">
        
          posts
      
        </Link>

        <Link  style={{marginLeft:"200px"}} href="/artical">
        
        articale
        
        </Link>
       </nav>
       
       {children}
       
       </body>
    </html>
  );
}

